# Generated by Django 2.1 on 2023-06-07 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pcost', models.CharField(max_length=50)),
                ('pquality', models.CharField(max_length=50)),
                ('pdec', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('paw', models.CharField(max_length=50)),
                ('mno', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Register'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admins.Products'),
        ),
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts_with_email', to='user.Register'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pimage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carts_with_pimage', to='admins.Products'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carts_with_pname', to='admins.Products'),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carts_with_price', to='admins.Products'),
        ),
        migrations.AddField(
            model_name='cart',
            name='uname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts_with_uname', to='user.Register'),
        ),
    ]
